export const images = [
  "/placeholder/1.svg",
  "/placeholder/2.svg",
  "/placeholder/3.svg",
  "/placeholder/4.svg",
  "/placeholder/5.svg",
  "/placeholder/6.svg",
  "/placeholder/7.svg",
  "/placeholder/8.svg",
  "/placeholder/9.svg",
  "/placeholder/10.svg",
  "/placeholder/11.svg",
  "/placeholder/12.svg",
  "/placeholder/13.svg",
  "/placeholder/14.svg",
  "/placeholder/15.svg",
  "/placeholder/16.svg",
  "/placeholder/17.svg",
  "/placeholder/18.svg",
  "/placeholder/19.svg",
  "/placeholder/20.svg",
  "/placeholder/21.svg",
  "/placeholder/22.svg",
  "/placeholder/23.svg",
  "/placeholder/24.svg",
];
export const randomImage = images[Math.floor(Math.random() * images.length)];
